/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Interfaz;

/**
 *
 * @author Internet
 */
public class Inter extends javax.swing.JFrame {
    
    public int numeros[]=new int[100];
    public int indice=0;
    public int aux;
    /**
     * Creates new form Inter
     */
    public Inter() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTextPane1 = new javax.swing.JTextPane();
        jPanel2 = new javax.swing.JPanel();
        txtNumero = new javax.swing.JTextField();
        Resultado = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        Agregar = new javax.swing.JButton();
        Mostrar = new javax.swing.JButton();
        Ordenar = new javax.swing.JButton();

        jScrollPane1.setViewportView(jTextPane1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtNumero.setBackground(new java.awt.Color(204, 255, 204));
        txtNumero.setFont(new java.awt.Font("Tempus Sans ITC", 0, 24)); // NOI18N
        txtNumero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNumeroActionPerformed(evt);
            }
        });
        txtNumero.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtNumeroKeyTyped(evt);
            }
        });
        jPanel2.add(txtNumero, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 327, 100));

        Resultado.setBackground(new java.awt.Color(204, 255, 204));
        Resultado.setFont(new java.awt.Font("Amiri", 3, 18)); // NOI18N
        jPanel2.add(Resultado, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 100, 327, 150));

        getContentPane().add(jPanel2, java.awt.BorderLayout.PAGE_START);

        jPanel6.setFont(new java.awt.Font("Segoe UI", 0, 48)); // NOI18N
        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setBackground(new java.awt.Color(255, 204, 204));
        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Opciones\n"));
        jPanel3.setToolTipText("");

        Agregar.setBackground(new java.awt.Color(102, 204, 255));
        Agregar.setText("Agregar");
        Agregar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                AgregarMouseEntered(evt);
            }
        });
        Agregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AgregarActionPerformed(evt);
            }
        });
        jPanel3.add(Agregar);

        Mostrar.setBackground(new java.awt.Color(0, 153, 255));
        Mostrar.setText("Mostrar");
        Mostrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                MostrarMouseEntered(evt);
            }
        });
        Mostrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MostrarActionPerformed(evt);
            }
        });
        jPanel3.add(Mostrar);

        Ordenar.setBackground(new java.awt.Color(0, 153, 255));
        Ordenar.setText("Ordenar");
        Ordenar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OrdenarActionPerformed(evt);
            }
        });
        jPanel3.add(Ordenar);

        jPanel6.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 327, -1));

        getContentPane().add(jPanel6, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void AgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AgregarActionPerformed
        // TODO add your handling code here:
        //Resultado.setText(txtNumero.getText());
       
        numeros[indice]=Integer.parseInt(txtNumero.getText());
        indice++;
        txtNumero.setText("");
    }//GEN-LAST:event_AgregarActionPerformed

    private void MostrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MostrarActionPerformed
        // TODO add your handling code here:
        /*
        String mensage=" ";
        for (int i=0;i<indice;i++){
            mensage=mensage+"("+numeros[i]+")";
        }
        Resultado.setText(mensage);
        */
        Resultado.setText("");
        for(int i=0;i<indice;i++){
            Resultado.setText(Resultado.getText()+numeros[i]+"  ");
        }
    }//GEN-LAST:event_MostrarActionPerformed

    private void txtNumeroKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNumeroKeyTyped
        // TODO add your handling code here:
        int key = evt.getKeyChar();
        
        boolean numeros_entrada = key >=48 && key <=57 || key ==45 ;
        
        if(!numeros_entrada)
        {
            evt.consume();
        }
    }//GEN-LAST:event_txtNumeroKeyTyped

    private void OrdenarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OrdenarActionPerformed
        // TODO add your handling code here:
        Resultado.setText(" ");
        for (int i = 0; i < indice; i++) {
            for (int j = 0; j < indice-1; j++) {
                if (numeros[j]>numeros[j+1]) {
                    aux=numeros[j];
                    numeros[j]=numeros[j+1];
                    numeros[j+1]=aux;
                }
            }
        }
        for (int i = 0; i < indice; i++) {
            Resultado.setText(Resultado.getText()+numeros[i]+" ");
        }
    }//GEN-LAST:event_OrdenarActionPerformed

    private void txtNumeroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNumeroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNumeroActionPerformed

    private void AgregarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AgregarMouseEntered

     Agregar.setBackground(new java.awt.Color(231,239,197));

                                            
    }//GEN-LAST:event_AgregarMouseEntered

    private void MostrarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MostrarMouseEntered
        // TODO add your handling code here:
       Mostrar.setBackground(new java.awt.Color(231,239,197));
    }//GEN-LAST:event_MostrarMouseEntered

     // TODO add your handling code here:
      
    private void MostrarMouseExited(java.awt.event.MouseEvent evt) {                                    
        // TODO add your handling code here:
        Mostrar.setBackground(new java.awt.Color(153,255,153));
    }                                   

    private void AgregarMouseExited(java.awt.event.MouseEvent evt) {                                    
        // TODO add your handling code here:
        Agregar.setBackground(new java.awt.Color(153,255,153));
    }                                   

    private void OrdenarMouseEntered(java.awt.event.MouseEvent evt) {                                     
        // TODO add your handling code here:
         Ordenar.setBackground(new java.awt.Color(231,239,197));
    }                                    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Inter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Inter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Inter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Inter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Inter().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Agregar;
    private javax.swing.JButton Mostrar;
    private javax.swing.JButton Ordenar;
    private javax.swing.JLabel Resultado;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextPane jTextPane1;
    private javax.swing.JTextField txtNumero;
    // End of variables declaration//GEN-END:variables
}
